---
##
# Git project deployment
##
- name: STAT | Stat git project directory
  stat:
    path: "{{ item.1.deploy_dir }}"
  register: deploy_git_directory_stat

- name: STAT | Stat symlink project directory
  stat:
    path: "{{ item.1.symlink_dir }}"
  register: symlink_directory_stat

- name: GIT | Deploy projects
  git:
    accept_hostkey: true
    repo: "{{ item.1.repository }}"
    dest: "{{ item.1.deploy_dir }}"
    version: "{{ item.1.branch }}"
  remote_user: "{{ item.1.remote_user }}"
  become: yes
  become_user: "{{ item.1.remote_user }}"
  become_flags: '-E'
  when: not deploy_git_directory_stat.stat.exists and not symlink_directory_stat.stat.exists

- name: COMPOSER | Composer install executions
  composer:
    command: install
    working_dir: "{{ item.1.deploy_dir }}"
    no_scripts: yes
  remote_user: "{{ item.1.remote_user }}"
  become: yes
  become_user: "{{ item.1.remote_user }}"
  become_flags: '-E'
  when: item.1.composer_install and not deploy_git_directory_stat.stat.exists and not symlink_directory_stat.stat.exists

- name: FILE | Symlink projects
  file:
    src: "{{ item.1.deploy_dir }}"
    dest: "{{ item.1.symlink_dir }}"
    state: link
  remote_user: "{{ item.1.remote_user }}"
  become: yes
  become_user: "{{ item.1.remote_user }}"
  become_flags: '-E'
  when: not deploy_git_directory_stat.stat.exists and not symlink_directory_stat.stat.exists
